name: Legacy Build

on:
  push:
    branches:
      - legacy

jobs:
  legacy:
    runs-on: windows-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Get Key files
        shell: bash
        run: |
          echo "${{ secrets.PFX }}" | base64 --decode > Seonglae.pfx
          echo "${{ secrets.ENV }}" > .env

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install npm dependencies
        shell: bash
        run: yarn

      - name: Run build task
        shell: bash
        run: |
          yarn build
          ln dist/Intuiter*.exe Intuiter.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: make artiface
          path: |
            dist
            Intuiter.exe
